import { writable } from 'svelte/store';

export const metaTitle = writable('Bṛhat')
export const metaDescription = writable('the Culture Engine')
export const metaUrl = writable('https://www.brhat.in')
export const metaImage = writable('')
export const metaType = writable('webpage')
export const anveshiChapter = writable('')
export const anveshiColor = writable('')
export const archiveFilter = writable('Dates')
export const authorName = writable('Select Writer')
export const categoryName = writable('Select Category')
export const tagName = writable('Select Tag')
export const dateBand = writable('All Posts')
export const thisLib = writable('')
export const drashtaDyn = writable('')
export const fontSize = writable('std')
export const dictionaryInput = writable('')
export const searchInput = writable('')
export const newsFilter = writable('Featured')