import type { SearchItem } from '$lib/types/SearchItem'

export const searchitems = [
{ "heading": "Create", "url": "/about" },
{ "heading": "Curate", "url": "/about" },
{ "heading": "Consult", "url": "/about" },
{ "heading": "Civilization is Culture in Action", "url": "/about" },
{ "heading": "It Needs Culture-Compatible Policy", "url": "/about" },
{ "heading": "The Work is Inter-generational", "url": "/about" },
{ "heading": "indica", "url": "/about" },
{ "heading": "sangam", "url": "/about" },
{ "heading": "pranava institute", "url": "/about" },
{ "heading": "whovr", "url": "/about" },
{ "heading": "eitri", "url": "/about" },
{ "heading": "voidpeak", "url": "/about" },
{ "heading": "vedicpond", "url": "/about" },
{ "heading": "Karnataka Chapter", "url": "/anveshi/karnataka" },
{ "heading": "Chamba Chapter", "url": "/anveshi/chamba" },
{ "heading": "Odisha Chapter", "url": "/anveshi/odisha" },
{ "heading": "Day 1 - Bhubhaneshvar", "url": "/anveshi/odisha" },
{ "heading": "Day 4 - Sringeri, Udupi", "url": "/anveshi/karnataka" },
{ "heading": "Day 1 - Chamba", "url": "/anveshi/chamba" },
{ "heading": "Day 2 - Khajjiar + Saho + towards Bharmour", "url": "/anveshi/chamba" },
{ "heading": "Day 3 – Bharmour", "url": "/anveshi/chamba" },
{ "heading": "Day 1 - Arrival at Hasan", "url": "/anveshi/karnataka" },
{ "heading": "Day 3 - Konark, Gop and Chaurasi", "url": "/anveshi/odisha" },
{ "heading": "Day 0 - Bhubhanveshvar", "url": "/anveshi/odisha" },
{ "heading": "Day 2 - Bhubhaneshvar Towards Konark", "url": "/anveshi/odisha" },
{ "heading": "Day 5 - Barkur", "url": "/anveshi/karnataka" },
{ "heading": "Day 0 - Assembly at Chamba", "url": "/anveshi/chamba" },
{ "heading": "Day 2 - Belur and Halebidu", "url": "/anveshi/karnataka" },
{ "heading": "Day 3 - Belavadi, Javagal", "url": "/anveshi/karnataka" },
{ "heading": "Konark", "url": "/anveshi/odisha" },
{ "heading": "Kattale Basadi", "url": "/anveshi/karnataka" },
{ "heading": "Nageshvara-Chennakeshava Temple complex, Mosale", "url": "/anveshi/karnataka" },
{ "heading": "Laxmi Narayan Temple Complex", "url": "/anveshi/chamba" },
{ "heading": "Champawati Temple", "url": "/anveshi/chamba" },
{ "heading": "Khajjiar Nag Temple", "url": "/anveshi/chamba" },
{ "heading": "Mukteshvara", "url": "/anveshi/odisha" },
{ "heading": "Megheshvara", "url": "/anveshi/odisha" },
{ "heading": "Sukasari", "url": "/anveshi/odisha" },
{ "heading": "Bucesvara Temple, Koravangala", "url": "/anveshi/karnataka" },
{ "heading": "Chowlikere Ganapathi Temple", "url": "/anveshi/karnataka" },
{ "heading": "Somnatheshvara, Barkur", "url": "/anveshi/karnataka" },
{ "heading": "Veera Narayana Temple, Belavadi", "url": "/anveshi/karnataka" },
{ "heading": "Hulikere Step Well, Halibedu", "url": "/anveshi/karnataka" },
{ "heading": "Chandrashekhar Temple, Saho", "url": "/anveshi/chamba" },
{ "heading": "Panchalingenshvara, Barkur", "url": "/anveshi/karnataka" },
{ "heading": "Sri Krishna Matha, Udupi", "url": "/anveshi/karnataka" },
{ "heading": "bṛhat anveṣī", "url": "/anveshi" },
{ "heading": "fractal maṇḍala", "url": "/mandala" },
{ "heading": "scrolls of āryavarta", "url": "/aryavarta" },
{ "heading": "bṛhad mṛdaṅga", "url": "/mrdanga" },
{ "heading": "open library", "url": "/openlibrary" },
{ "heading": "Harirai Temple, Chamba", "url": "/anveshi/chamba" },
{ "heading": "Chamuda Devi Temple, Chamba", "url": "/anveshi/chamba" },
{ "heading": "Chaurasi Temple, Bharmour", "url": "/anveshi/chamba" },
{ "heading": "Brahmani Mata Temple, Bharmour", "url": "/anveshi/chamba" },
{ "heading": "Chennakeshava Temple, Belur", "url": "/anveshi/karnataka" },
{ "heading": "Shri Sharada Matha, Sringeri", "url": "/anveshi/karnataka" },
{ "heading": "Lakshmi Narasimha, Javagal", "url": "/anveshi/karnataka" },
{ "heading": "Vajreshvari Devi, Chamba", "url": "/anveshi/chamba" },
{ "heading": "Jain Temple", "url": "/anveshi/karnataka" },
{ "heading": "Ananta Basudeva", "url": "/anveshi/odisha" },
{ "heading": "Parashurameshvara", "url": "/anveshi/odisha" },
{ "heading": "Kedara Gouri", "url": "/anveshi/odisha" },
{ "heading": "Siddheshvara", "url": "/anveshi/odisha" },
{ "heading": "Bhaskareshvara", "url": "/anveshi/odisha" },
{ "heading": "Brahmeshvara", "url": "/anveshi/odisha" },
{ "heading": "Mahavinayak", "url": "/anveshi/odisha" },
{ "heading": "Baital Deula", "url": "/anveshi/odisha" },
{ "heading": "Chitrakarini", "url": "/anveshi/odisha" },
{ "heading": "Chausath Yogini", "url": "/anveshi/odisha" },
{ "heading": "Gangeshvari", "url": "/anveshi/odisha" },
{ "heading": "Barahi Devi, Chaurasi", "url": "/anveshi/odisha" },
{ "heading": "Jagannath Temple", "url": "/anveshi/odisha" },
{ "heading": "Sakshi Gopal", "url": "/anveshi/odisha" },
{ "heading": "Śakti Devi Temple, Chhatrari", "url": "/anveshi/chamba" },
{ "heading": "Rajarani", "url": "/anveshi/odisha" },
{ "heading": "Lingaraja", "url": "/anveshi/odisha" },
{ "heading": "Logic of Rig Vedic Geography", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Ikshvakus in the Rig Veda", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Identity of the Enemies of Sudas", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Dravidian Connections to Rig Veda and Harappa", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Dravidian and Pan-Indian Nature of Hinduism", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Pūrva-pakṣa of Sheldon Pollock's use of Chronology", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Vanishing Rivers Yesterdays Sarasvati Todays Ganga", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Sarasvatī in the Mahābhārata - A Study", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Sarasvati River Issues And Debates", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Sarasvati Palaeochannel Groundwater Remote Sensing", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "On The Preliminary Periodization Of The Harappan Civilization", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Vedic Roots Of Early Tamil Culture", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Indo Aryans Of Ancient South Asia", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Horse And The Aryan Debate", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Coming of Aryans to Iran and India", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "policy research", "url": "/about/areas/policyresearch" },
{ "heading": "creatives", "url": "/about/areas/culturecreatives" },
{ "heading": "Rig Vedic History", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Rama's Realm", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "On the Battle of Ten Kings", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "On Talageri", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Non Aryan Names In Rig Veda", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "New Perspectives On Our Cultural Pasts", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Vedic Genetics Cow Omni Form Decipherment", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Prehistoric Peopling Of Southeast Asia", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Himalayas As A Prehistoric Corridor", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Formation of Human Populations in South and Central Asia", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Eastern Himalayan Corridor In Prehistory", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Reconstructing The Population History Of the Gond", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Prehistoric Skeletal Record of Man in South Asia", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Prehistoric Human Colonisation Of India", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Origin Of Rice", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "On Peopling of India Ancient Genetics Perspectives", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Linguistic Population Prehistory Of The Greater Himalaya Region", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Haplogroup R1A", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Glimpses Of The Ethnolinguistic Prehistory of Northeastern India", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Genetics And The Aryan Issue", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Genetics And AIT, Look Again", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Genetic And Linguistic Non Correspondence", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Genes, Peoples and Languages", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Worked Bone Industry", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Sanauli Chariot And Its Archaeological and Historical Context", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Harappan Heritage And The Aryan Problem", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Epistemological Event Horizon In Archaeology", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Sibri and the South Cemetery of Mehrgarh", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Sanauli a Late Harappan Burial Site", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Origin Of Early Harappan Cultures In The Sarasvati Valley", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Indus Valley Electron Microscopy And Crystallography", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Vishnu In Rigveda", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "True Meaning Of Ashva", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Indo European Cloudland", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The Debate Between Talageri and Hoch", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "The A of ABC of Indian chronology: Dimensions of the Aryan problem revisited in 2017", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Short Notes On Paninian Sanskrit Versus Mature Harappan", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Rigvedic And Written Mature Harappan 2", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Rigvedic And Written Mature Harappan 1", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "On the Meaning of Hymns to Maruts in the Rigveda", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Munda Languages Are Father Tongues But Japanese and Korean Are Not", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Methodological Issues In The Indo European Debate", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Iranians Vs Vedic Aryans", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Hindu Dharma", "url": "/openlibrary/books" },
{ "heading": "Indo Uralic Indo Anatolian Indo Tocharian", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Images Of Solar Bulls", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Harappan Discontinuity 4500 Ybp", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "In Search Of The Oldest Common Indo European Urheimat", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Antecedents Of Rig Vedic Religion", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Excavating Vedic Harappans", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Coexistence of Culture and Civilization ISC and OCP", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Animal Subsistence In Ganga Valley", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Eurasian Spreadzone And IE Dispersal", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Ancient Cattle Genomics", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Epicenter of the Indo-European Linguistic Spread", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Chronology And Culture History In The Indus Valley", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "AIT And Linguistics", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Discovering The Sarasvati River", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Chera Chola Pandya Using Archaeological Evidence to Identify the Tamil Kingdoms of Early Historic South India", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Absence Of Sword From Rig Veda", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Demilitarizing The Rigveda", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Autochthonous Aryans", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "A Timeline Of Ayodhya", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Decipherment Of Indus Valley Vedic Seals", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Asura And Its Derivatives In Rigveda", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "A Prehistoric Thoroughfare Between The Ganges and the Himalaya", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "From Sarasvati To Ganga", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Decipherment Of Indus Valley Seals", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Astronomical Chronology Of Vedic Literature", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "A Note On PIE And Nuclear Nostratic", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Five Waves Of Indo European Expansion", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Converging Views On Asian Prehistory", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Aryans And The Indus Civilization", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Females In Rig Veda", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Continuity Of European Languages", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Archaeological and Anthropological Studies on the Harappan Cemetery of Rakhigarhi", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "A Dravido Harappan Connection The Issue", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Indian Historical Writing", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Fabricating Evidence In Support Of The AIT", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Complex Genetic Origin of Indian Populations and Its Implications", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Archaeobotany Of Ganga Plain 2500 BC", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Scratching my head! — Criticism of Narsimhan VM et al 2019", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Chronology Of Kings Puranic Kings and Rigvedic Rshis", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Aryas, Dasas and Dasyus", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Aryan Story vs True Aryan History", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Varsagira Battle", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Rakhigarhi and After", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Out of India Case in Full", "url": "/openlibrary/specials/aryanissue" },
{ "heading": "Hindu Sikh Relationship", "url": "/openlibrary/books" },
{ "heading": "Hindu View of Christianity and Islam", "url": "/openlibrary/books" },
{ "heading": "On Hinduism, Reviews and Reflections", "url": "/openlibrary/books" },
{ "heading": "Understanding the Hadith", "url": "/openlibrary/books" },
{ "heading": "Where Are They: Communists Under Communism", "url": "/openlibrary/books" },
{ "heading": "Whither Sikhism", "url": "/openlibrary/books" },
{ "heading": "A Scheme for Knowledge Representation in Samskritam", "url": "/openlibrary/books" },
{ "heading": "Bhartṛhari’s Linguistic Ontology and the Semantics of Ātmanepada", "url": "/openlibrary/books" },
{ "heading": "Essential Coomaraswamy", "url": "/openlibrary/books" },
{ "heading": "Shri Ram Swarup", "url": "/drashta/course/shriramswarup" },
{ "heading": "The Indo European Language Family", "url": "/openlibrary" },
{ "heading": "Sita Ram Goel", "url": "/drashta/course/sitaramgoel" },
{ "heading": "Hindu Iconography", "url": "/drashta/course/hinduiconography" },
{ "heading": "The Knowledge Structure in the Amarakosha", "url": "/openlibrary/books" },
{ "heading": "Vākyapadīya", "url": "/openlibrary/books" },
{ "heading": "Future of Mankind", "url": "/openlibrary/books" },
{ "heading": "Historical Methods", "url": "/openlibrary/books" },
{ "heading": "Ideas of History in Sanskrit Literature", "url": "/openlibrary/books" },
{ "heading": "Introduction to IKS (Indian Knowledge Systems)", "url": "/openlibrary/books" },
{ "heading": "Language and Reality: World View of Nyaya-Vaisesika", "url": "/openlibrary/books" },
{ "heading": "On the Nature of Mathematics and Scientific Knowledge in Indian Tradition", "url": "/openlibrary/books" },
{ "heading": "Nasadiya Sukta from an Adhyatmika Perspective", "url": "/openlibrary/books" },
{ "heading": "Hindu Temples Vol 1", "url": "/openlibrary/books" },
{ "heading": "Hindu Temples Vol 2", "url": "/openlibrary/books" },
{ "heading": "Geography of the Puranas", "url": "/openlibrary/books" },
{ "heading": "How I Became a Hindu", "url": "/openlibrary/books" },
{ "heading": "The Secret of the Veda", "url": "/openlibrary/books" },
{ "heading": "Arthashastra", "url": "/openlibrary/books" },
{ "heading": "Amarakośaḥ Devanāgarī", "url": "/openlibrary/books" },
{ "heading": "Amarakosha English Translation", "url": "/openlibrary/books" },
{ "heading": "Illustrated Amarakosha in 4 Languages", "url": "/openlibrary/books" },
{ "heading": "Introduction to Sanskrit Shabdamitra", "url": "/openlibrary/books" },
{ "heading": "A Practical Sanskrit Introductory", "url": "/openlibrary/books" },
{ "heading": "Sanskrit Grammar", "url": "/openlibrary/books" },
{ "heading": "The Vedas", "url": "/openlibrary/books" },
{ "heading": "Aurobindo's Cyclical Theory of History", "url": "/openlibrary/books" },
{ "heading": "On the Chronological Framework for Indian Culture", "url": "/openlibrary/books" },
{ "heading": "History without Chronology", "url": "/openlibrary/books" },
{ "heading": "Hindu Dharma", "url": "/openlibrary/books" },
{ "heading": "Rediscovering India", "url": "/openlibrary/books" },
{ "heading": "Essays on Tradition, Recovery and Freedom", "url": "/openlibrary/books" },
{ "heading": "Select Essays from Comparative Civilizations Review: pre-2000", "url": "/openlibrary/books" },
{ "heading": "Select Essays from Comparative Civilizations Review: 2001-2010", "url": "/openlibrary/books" },
{ "heading": "Select Essays from Comparative Civilizations Review: 2011-2019", "url": "/openlibrary/books" },
{ "heading": "Select Essays from Comparative Civilizations Review: post-COVID", "url": "/openlibrary/books" },
{ "heading": "Hindustani Music", "url": "/openlibrary/books" },
{ "heading": "On Natyashastra", "url": "/openlibrary/books" },
{ "heading": "Art Experience", "url": "/openlibrary/books" },
{ "heading": "The Kalās", "url": "/openlibrary/books" },
{ "heading": "64 Arts in Ancient India", "url": "/openlibrary/books" },
{ "heading": "The Crisis of Hinduism", "url": "/openlibrary/books" },
{ "heading": "Gandhi’s Theory of Society and Our Times", "url": "/openlibrary/books" },
{ "heading": "Harivaṃśa Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Agni Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Brahma Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Brahmāṇḍa Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Garuda Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Mārkaṇḍeya Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Matsya Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Śiva Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Vāyu Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Viṣṇu Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Padma Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Nārada Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Varaha Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Skanda Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Vāmana Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Bhagavata Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Kūrma Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Liṅga Purāṇa", "url": "/openlibrary/books" },
{ "heading": "Aitareya Upaniṣad", "url": "/openlibrary/books" },
{ "heading": "Chāndogya Upaniṣad", "url": "/openlibrary/books" },
{ "heading": "Kena Upaniṣad", "url": "/openlibrary/books" },
{ "heading": "Kaṭha Upaniṣad", "url": "/openlibrary/books" },
{ "heading": "Taittirīya Upaniṣad", "url": "/openlibrary/books" },
{ "heading": "Iṣā Upaniṣad", "url": "/openlibrary/books" },
{ "heading": "Bṛhadāraṇyaka Upaniṣad", "url": "/openlibrary/books" },
{ "heading": "Māṇdūkya Upaniṣad", "url": "/openlibrary/books" },
{ "heading": "Muṇḍaka Upaniṣad", "url": "/openlibrary/books" },
{ "heading": "Praśna Upaniṣad", "url": "/openlibrary/books" },
{ "heading": "Sushant Gangoli", "url": "/dhiti/authors/sushantgangoli" },
{ "heading": "Anshuman Panda", "url": "/dhiti/authors/anshumanpanda" },
{ "heading": "Akshay Jha", "url": "/dhiti/authors/akshayjha" },
{ "heading": "Abhishek Doshi", "url": "/about" },
{ "heading": "Nivedita Tiwari", "url": "/dhiti/authors/niveditatiwari" },
{ "heading": "Anurag Shukla", "url": "/dhiti/authors/anuragshukla" },
{ "heading": "Kavita Krishna Meegama", "url": "/dhiti/authors/kavitakrishna" },
{ "heading": "Amritanshu Pandey", "url": "/dhiti/authors/amritanshupandey" },
{ "heading": "Pankaj Saxena", "url": "/dhiti/authors/pankajsaxena" },
{ "heading": "Reena George", "url": "/about/#team" },
{ "heading": "Raghava Krishna", "url": "/dhiti/authors/raghavakrishna" },
{ "heading": "SrīRāmacaritamānasa and Śiva.", "url": "https://youtube.com/@brhat" },
{ "heading": "Rāmacaritamānasa and Ecology", "url": "https://youtube.com/@brhat" },
{ "heading": "Rāmacaritamānasa | The voice of our civilisational conscience", "url": "https://youtube.com/@brhat" },
{ "heading": "Founder's Journey", "url": "https://youtube.com/@brhat" },
{ "heading": "Aesthetics in culture and policy", "url": "https://youtube.com/@brhat" },
{ "heading": "Beauty in Policy", "url": "https://youtube.com/@brhat" },
{ "heading": "Inheriting colonizers policy", "url": "https://youtube.com/@brhat" },
{ "heading": "3 Areas + 3 Actions of Bṛhat", "url": "https://youtube.com/@brhat" },
{ "heading": "Culture in Policy", "url": "https://youtube.com/@brhat" },
{ "heading": "गणतंत्र दिवस 2023", "url": "https://youtube.com/@brhat" },
{ "heading": "Bṛhat Anveṣī Hoysala Sculpture II", "url": "https://youtube.com/@brhat" },
{ "heading": "Bṛhat Anveṣī Hoysala Sculpture", "url": "https://youtube.com/@brhat" },
{ "heading": "विजयनी तेरी पताका | महादेवी वर्मा", "url": "https://youtube.com/@brhat" },
{ "heading": "Dhārmika Exceptionalism & Low Policy Currency", "url": "https://youtube.com/@brhat" },
{ "heading": "Power of Liberal Atheism", "url": "https://youtube.com/@brhat" },
{ "heading": "Bṛhat's Work", "url": "https://youtube.com/@brhat" },
{ "heading": "Brhat: An organisation working on Culture Compatible Public Policy | Raghava Krishna", "url": "https://youtube.com/@brhat" },
{ "heading": "The long Arc of Islam | Pankaj Saxena", "url": "https://youtube.com/@brhat" },
{ "heading": "Unfinished Agendas of Political Islam - Lebanon | Pankaj Saxena", "url": "https://youtube.com/@brhat" },
{ "heading": "Svayambodha and Shatrubodha: Two Wheels of Civilization | Pankaj Saxena", "url": "https://youtube.com/@brhat" },
{ "heading": "Unfinished Agendas of Political Islam - Armenia and Turkey | Pankaj Saxena", "url": "https://youtube.com/@brhat" },
{ "heading": "Appeal to Teachers and Academia", "url": "https://youtube.com/@brhat" },
{ "heading": "Vision and Challenges of IKS", "url": "https://youtube.com/@brhat" },
{ "heading": "Why IKS? Next stage of evolution", "url": "https://youtube.com/@brhat" },
{ "heading": "Policy changes required for IKS", "url": "https://youtube.com/@brhat" },
{ "heading": "Strategy and Roadmap for IKS", "url": "https://youtube.com/@brhat" },
{ "heading": "Dhara Conference", "url": "https://youtube.com/@brhat" },
{ "heading": "Idea of Scale in IKS", "url": "https://youtube.com/@brhat" },
{ "heading": "Strategic Context of IKS | Raghava Krishna", "url": "https://youtube.com/@brhat" },
{ "heading": "कोकिल । आचार्य महावीर प्रसाद द्विवेदी", "url": "https://youtube.com/@brhat" },
{ "heading": "नर हो न निराश । मैथिलीशरण गुप्त", "url": "https://youtube.com/@brhat" },
{ "heading": "कामायनी । जयशंकर प्रसाद", "url": "https://youtube.com/@brhat" },
{ "heading": "स्वतंत्रता दिवस 2022", "url": "https://youtube.com/@brhat" },
{ "heading": "जो तुम आ जाते एक बार । महादेवी वर्मा", "url": "https://youtube.com/@brhat" },
{ "heading": "Pūrṇa", "url": "https://youtube.com/@brhat" },
{ "heading": "Śūnya", "url": "https://youtube.com/@brhat" },
{ "heading": "Cakra", "url": "https://youtube.com/@brhat" },
{ "heading": "Bindu", "url": "https://youtube.com/@brhat" },
{ "heading": "Garbha", "url": "https://youtube.com/@brhat" },
{ "heading": "Nābhi", "url": "https://youtube.com/@brhat" },
{ "heading": "Puruṣa", "url": "https://youtube.com/@brhat" },
{ "heading": "Stambha", "url": "https://youtube.com/@brhat" },
{ "heading": "Bīja Part II", "url": "https://youtube.com/@brhat" },
{ "heading": "Bīja Part I", "url": "https://youtube.com/@brhat" },
{ "heading": "Will I Recommend Bṛhat | Parvathi Subramaniam", "url": "https://youtube.com/@brhat" },
{ "heading": "Barkur Temples Talk | Parvathi Subramaniam", "url": "https://youtube.com/@brhat" },
{ "heading": "Kṛṣṇa Kṛṣṇa Mukuṃdā Bhajan | Parvathi Subramaniam", "url": "https://youtube.com/@brhat" },
{ "heading": "Vanamali Radha Ramana Bhajan | Parvathi Subramaniam", "url": "https://youtube.com/@brhat" },
{ "heading": "Udupi Sri Krishna Matha | Parvathi Subramaniam", "url": "https://youtube.com/@brhat" },
{ "heading": "Ambā Parameśvarī Bhajan | Parvathi Subramaniam", "url": "https://youtube.com/@brhat" },
{ "heading": "Sringeri Śāradambā and Bhajan | Parvathi Subramaniam", "url": "https://youtube.com/@brhat" },
{ "heading": "Kṛṣṇa Kṛṣṇa Vāsudev Bhajan | Parvathi Subramaniam", "url": "https://youtube.com/@brhat" },
{ "heading": "Belavadi Veera Narayana Temple | Parvathi Subramaniam", "url": "https://youtube.com/@brhat" },
{ "heading": "How Karnataka Chapter was designed | Parvathi Subramaniam", "url": "https://youtube.com/@brhat" },
{ "heading": "Bṛhat Anveṣī Experience - Sankalpita Singh", "url": "https://youtube.com/@brhat" },
{ "heading": "anveṣī", "url": "/anveshi" },
{ "heading": "introduction", "url": "/rta/intro" },
{ "heading": "karnataka", "url": "/anveshi/karnataka" },
{ "heading": "chamba", "url": "/anveshi/chamba" },
{ "heading": "odisha", "url": "/anveshi/odisha" },
{ "heading": "prologue", "url": "/rta/prologue" },
{ "heading": "svataḥsiddha", "url": "/about/svatahsiddha" },
{ "heading": "dharma is design", "url": "/rta/dharmaisdesign" },
{ "heading": "nasadīya", "url": "/aryavarta/chapter/03" },
{ "heading": "the macrohistoric case", "url": "/mandala/macrohistoriccase" },
{ "heading": "about", "url": "/about" },
{ "heading": "history vs. itihāsa", "url": "/mandala/historyvsitihasa" },
{ "heading": "civilizational consciousness", "url": "/mandala/indiancivcon" },
{ "heading": "ratha as bīja", "url": "/mandala/rathaasbija" },
{ "heading": "ancestors outside of time", "url": "/mandala/ancestors" },
{ "heading": "Akshay Shankar", "url": "/dhiti" },
{ "heading": "civilizational moment", "url": "/about/anatomy" },
{ "heading": "avatāra in you", "url": "/mandala/ramasjourney" },
{ "heading": "team", "url": "/about/#team" },
{ "heading": "partners", "url": "/about/#partners" },
{ "heading": "advisors", "url": "/about/#advisors" },
{ "heading": "nāmarūpa", "url": "/about/namelogo" },
{ "heading": "dhīti", "url": "/dhiti" },
{ "heading": "leadership development", "url": "/about/areas/leadershipdevelopment" },
{ "heading": "Prabhav Paturi", "url": "/dhiti" },
{ "heading": "ṛta in design", "url": "/rta" },
{ "heading": "Ghor Angirasa", "url": "/dhiti" },
{ "heading": "design at bṛhat", "url": "/rta/designatbrhat" },
{ "heading": "Kate Herst", "url": "/dhiti" },
{ "heading": "Jash Dholani", "url": "/dhiti" },
{ "heading": "Shri Ramachandra Roddam", "url": "/dhiti" },
{ "heading": "faq", "url": "/anveshi/#faqgrid" },
{ "heading": "travel diaries", "url": "/anveshi/#diaries" },
{ "heading": "Rāmāyaṇa", "url": "/drashta/course/valmikiramayana" },
{ "heading": "what śrī kṛṣṇa means to us", "url": "/about/whatkrishnameanstous" },
{ "heading": "pratijñā", "url": "/about/values" },
{ "heading": "schools of thought", "url": "/drashta/schools" },
{ "heading": "bṛhat draṣṭā", "url": "/drashta" },
{ "heading": "synaptic reconnection", "url": "/mandala/synrec" },
{ "heading": "caturasūtra - 4 aphorisms", "url": "/mandala/aphorisms" },
{ "heading": "lore", "url": "/aryavarta/lore" },
{ "heading": "sūta and sudā", "url": "/aryavarta/chapter/02" },
{ "heading": "kaśyapa's lament", "url": "/aryavarta/chapter/01" },
{ "heading": "Sai Priya Chodavarapu", "url": "/dhiti/authors/saipriya" },
]